export enum LocationActionTypes {
  SET_LOCATION = 'SET_LOCATION',
  FETCH_SOMETHING_LOADING_START = 'FETCH_SOMETHING_LOADING_START',
  FETCH_SOMETHING_LOADING_DONE = 'FETCH_SOMETHING_LOADING_DONE',
  FETCH_SOMETHING_ERROR = 'FETCH_SOMETHING_ERROR',
}
